version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitor:/etc/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin   # default user=admin, pass=admin (change as you like)
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
